// Automatically generated by makemoduledefs.py.

#if (1)
    extern const struct _mp_obj_module_t fb_cmodule;
    #define MODULE_DEF_MP_QSTR_FB { MP_ROM_QSTR(MP_QSTR_fb), MP_ROM_PTR(&fb_cmodule) },
#else
    #define MODULE_DEF_MP_QSTR_FB
#endif


#define MICROPY_REGISTERED_MODULES \
    MODULE_DEF_MP_QSTR_FB \
// MICROPY_REGISTERED_MODULES
