#!/bin/bash
# SPDX-License-Identifier: Apache-2.0

ROOT="$(realpath $(dirname $BASH_SOURCE)/..)"
WORKSPACE="$(realpath $ROOT/..)"

DOCKER_IMAGE="swedishembedded/build:v0.24.5"
COMMAND="$@"

docker run -ti --rm \
	-v $WORKSPACE:$WORKSPACE \
	$DOCKER_IMAGE /bin/bash -c \
	"cd $ROOT; sudo -u user $COMMAND"
